### ISSUE TITLE
Get all files at once when using multiple

### ISSUE THREAD

**Issue by bxnkole** [fvilers/angular-file-picker#13]

**Comment by fvilers** [comment]
Hi! Thanks for the suggestion. Could you give an example why you'd like to have only one event with all files? Why is it problematic to have "n" events?

**Comment by bxnkole** [comment]
Thanks for your feedback. @fvilers 

Okay. So I have a use case  where I need to open a file dialog  for the user to select multiple files. Lets say I have a handler method called `uploadFiles`. Currently, the uploadFiles method is invoked for every file the user selects. I need all the files to go to the backend at once. My current workaround is pushing all selected `PickedFile `objects to an array and displaying another button for the user to upload the selectedFiles to my backend.

**Comment by fvilers** [comment]
OK, I get it. I'd like to keep the available properties on the directive as small as possible, especially if it depends on the value of another one. So I prefer not to add a property to change the current behavior. What do you think of adding two events: one when the directive starts reading files and on when it has ended reading all of them?

**Comment by bxnkole** [comment]
Yeah. I understand your concern. For the events, do you mean like an EventEmitter?

**Comment by fvilers** [comment]
Yes, 2 events on which you can listen. When the last on triggers, you know that your array is complete. This way, I don't add a breaking changes on the current version.

**Comment by bxnkole** [comment]
Ok. So at what point will the array of PickedFile objects be exposed? I assume this will happen in the last event?

**Comment by fvilers** [comment]
You'll continue as you did before, for each filePick event, you store the file in an array. But when the readEnd event triggers, you can upload the file array to your back-end server.

**Comment by bxnkole** [comment]
Ok. I think that works. Thanks for your support.

**Comment by fvilers** [comment]
I've published a 2.2.0 version on NPM. Feel free to test it and give some feedback :-)
