### ISSUE TITLE
AOT issue

### ISSUE THREAD

**Issue by andrei-sadagurschi** [fvilers/angular-file-picker#15]
I am getting the following error when building with AOT:

Angular compilation done, starting webpack bundling.
```
Error: Metadata version mismatch for module /Users/.../node_modules/angular-file-picker/node_modules/@angular/core/core.d.ts, found version 4, expected 3
    at StaticSymbolResolver.getModuleMetadata (/Users/.../node_modules/@angular/compiler/@angular/compiler.es5.js:25586:7)
    at StaticSymbolResolver._createSymbolsOf (/Users/.../node_modules/@angular/compiler/@angular/compiler.es5.js:25374:10)
    at StaticSymbolResolver.getSymbolsOf (/Users/.../node_modules/@angular/compiler/@angular/compiler.es5.js:25355:12)
    at /Users/.../node_modules/@angular/compiler/bundles/compiler.umd.js:24241:30
    at Array.forEach (<anonymous>)
    at extractProgramSymbols (/Users/.../node_modules/@angular/compiler/@angular/compiler.es5.js:24210:55)
    at AotCompiler.analyzeModulesAsync (/Users/.../node_modules/@angular/compiler/@angular/compiler.es5.js:23766:7)
    at CodeGenerator.codegen (/Users/.../packages/compiler-cli/src/codegen.ts:41:10)
    at /Users/.../node_modules/src/main.ts:20:84
    at Object.main (/Users/.../tools/@angular/tsc-wrapped/src/main.ts:136:12)
    at Object.runInternal (/Users/.../node_modules/src/main.ts:25:10)
    at /Users/.../node_modules/src/plugin.ts:64:21
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

angular-file-picker version 2.2.0.
Angular version 4.4.6.
npm version 5.5.1.
node version 8.9.0.

**Comment by andrei-sadagurschi** [comment]
Same problem with angular-file-dropzone.

**Comment by fvilers** [comment]
Hi! Thanks for your report. It looks like the latest build of these librairies are not compatible with Angular 4.x. I'll look into it to see I can made them work with prior version of Angular 5.x.

**Comment by fvilers** [comment]
Hi, I'm sorry for the delay but I hadn't so much time to look into this. Does upgrade to Angular 5 is an issue for you? It'd fix AOT build.

I'm considering downgrading the peer dependencies required when I have a couple of free hours.

**Comment by bvedam** [comment]
Hi - I had the same issue with Angular 4.x version. Upgraded to v5 which forced me to use material and cdk versions 5.0.1 to avoid peer dependency. Now they get along well, but when I install file-picker it complains of peer dependency error 
+-- UNMET PEER DEPENDENCY @angular/common@5.1.1
+-- UNMET PEER DEPENDENCY @angular/core@5.1.1
`-- angular-file-picker@2.2.0

**Comment by fvilers** [comment]
I'll try to clean up the dependencies hell I've put there ASAP but its December and I need to find some time to work on this.

**Comment by bvedam** [comment]
Actually I tried Angular 5.0.1 instead of 5.1.1 and it all worked. Thanks.

**Comment by fvilers** [comment]
@bvedam Great, but I still need to clean up the mess. Hopefully, next weekend.

**Comment by saschwarz** [comment]
I've tried @angular 5.0.1 and running ngc I get this error (also with angular-filedrop-zone):

```$ node_modules/.bin/ngc
Error: Error encountered resolving symbol values statically. Lambda not supported (position 194:31 in the original .ts file), 
resolving symbol NgModule in /Users/saschwarz/dev/agility-course-master/agility-course-master/node_modules/angular-file-picker/node_modules/@angular/core/core.d.ts, 
resolving symbol AngularFilePickerModule in /Users/saschwarz/dev/agility-course-master/agility-course-master/node_modules/angular-file-picker/angular-file-picker.d.ts, 
resolving symbol AngularFilePickerModule in /Users/saschwarz/dev/agility-course-master/agility-course-master/node_modules/angular-file-picker/angular-file-picker.d.ts
```

**Comment by fvilers** [comment]
I'll definitely look into it. Sorry for the dealy, I'm quite busy these days. Stay tuned.

**Comment by saschwarz** [comment]
For now, I've ended up copying the `lib` directory into my app and it is compiling fine.

**Comment by fvilers** [comment]
Hi there, I know this issue has been open for too long but I finally managed to get some time to work on it. While looking to AOT optimization, and about library building best practices, I came to the conclusion that I should start from scratch and to merge the directives I use for managing files in Angular into the same library.

This project will be discontinued, could you please update your application to use https://www.npmjs.com/package/ngx-file-helpers from now?

Thanks!
Fabian
