### ISSUE TITLE
Instructions in README are wrong about Import

### ISSUE THREAD

**Issue by sindhu732** [fvilers/angular-file-picker#16]
import { AngularFilePickerModule } from 'angular-file-picker';

@NgModule({
.....
imports: [ .....
    AngularFilePickerModule,
    ....]

This is the correct way to import it into the project. In the README here, just FirePickerModule is used. This is inconsistent with the code in this library.

**Comment by fvilers** [comment]
Hi! Thanks for your suggestion but I'm not sure to understand what's the issue? You'd prefer that the module is named `AngularFilePickerModule` instead of `FilePickerModule`? I don't see any added value, but maybe you have something in mind.

**Comment by justinwilloughby** [comment]
Can confirm, the `FilePickerModule`  is not exported from your library. Instead you export the `AngularFilePickerModule`. You may have just forgot what you named it when you wrote the documentation. In other words, if you try and import your module the way your documentation says to, it will not work.

**Comment by fvilers** [comment]
Thanks for the precision, I'll get that fixed ASAP.

**Comment by ghost** [comment]
Yes! I imported `AngularFilePickerModule` instead and it seem to work.
