### ISSUE TITLE
events not firing when used on dialg component

### ISSUE THREAD

**Issue by ortegamediatasoft** [fvilers/angular-file-picker#18]
As the title says, i am able to open de system file dialog when the button is in the component used by the module that imports this repo, but, when i open a dialog and try to launch on that dialog, the button does not react, lets say, a have my page, showing a list of files, and a button that opens a dialog to fill in some file info, and the button to pick the file from file system, well, the button on the list opens the system dialog, bot the same button on the component opened via dialog didnt react

i am using this code
<button
  type="button"
  ngFilePicker
  (filePick)="filePicked($event)">
    Seleccionar archivo
</button>

i am using the release 2.2.0
and angular 5, but as far as i remember, it was the same thing when on angular 4 and release 1.2.0
if you need more info i am just a comment of distance, thanks for reading.

**Comment by fvilers** [comment]
Hi ! Thanks for your report. I'm sorry, but I don't understand exactly what's not working. Maybe could you create a reproduction of the issue on [Plunkr](https://plnkr.co/) ?

**Comment by ortegamediatasoft** [comment]
i forked this repo, replicated my situation based on your config, and it seems to work on on the same scenario, so its mostly related to my implementation, strange thing, this button was inside a .form-group, when i deleted this class of the direct wrapper, it started to work, maybe a bind to another events was firing
