### ISSUE TITLE
Not compatible with Angular Material 1.0.

### ISSUE THREAD

**Issue by darickc** [fvilers/angular-file-picker#21]
With the release of Angular 5.1, Angular Material 1.0 was also released.  This is still referencing the beta packages and causes errors when using Angular Material 1.0.

**Comment by fvilers** [comment]
Hi! Thanks for your report. Having a dependency on Angular Material is something I really do not want (and that the library does not need) but its related on how I built the lib. I'll try to fix that as it's also disturbing the AOT process.

**Comment by fvilers** [comment]
Hi there, I know this issue has been open for too long but I finally managed to get some time to work on it. While looking to AOT optimization, and about library building best practices, I came to the conclusion that I should start from scratch and to merge the directives I use for managing files in Angular into the same library.

This project will be discontinued, could you please update your application to use https://www.npmjs.com/package/ngx-file-helpers from now?

Thanks!
Fabian
