### ISSUE TITLE
When selecting the same file a second time nothing happens

### ISSUE THREAD

**Issue by CramericaIndustries** [fvilers/angular-file-picker#4]
At least on Chrome the inputs change event won't fire when you select the same file a second time in a row.
The solution is to set the input.value property to null before opening the file selection dialog.

```
  @HostListener('click')
  browse() {
    this.input.value = null;
    this.renderer.invokeElementMethod(this.input, 'click');
  }
```

**Comment by fvilers** [comment]
Thanks for the suggestion. I added a reset method that you can manually call via a ViewChild property to reset the current value.

**Comment by fvilers** [comment]
Version 1.2.0 has been released on NPM.
